### ISSUE TITLE
PIM Caught panic while installing PE on remote server from Windows 11

### ISSUE THREAD

**Issue by etec-masterofsynapse** [puppetlabs/puppet-enterprise_issues#43]
## Describe the Bug
I tried to install PE via PIM for Windows, and got this error:

```
Caught panic:

strings: negative Repeat count

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:16 +0x13
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /home/runner/work/installer/installer/vendor/github.com/charmbracelet/bubbletea/tea.go:478 +0x91
panic({0xadd260?, 0xe19030?})
        /opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:920 +0x270
strings.Repeat({0xe17f98?, 0xc000457080?}, 0x0?)
        /opt/hostedtoolcache/go/1.21.10/x64/src/strings/strings.go:554 +0x318
github.com/puppetlabs/installer/wizard/components/PE/screens/progress.resultMsg.String({{0x0?, 0xc00030a0c0?}})
        /home/runner/work/installer/installer/wizard/components/PE/screens/progress/progress.go:80 +0xa7
github.com/puppetlabs/installer/wizard/components/PE/screens/progress.(*Model).View(0xc00027e000)
        /home/runner/work/installer/installer/wizard/components/PE/screens/progress/progress.go:337 +0x3d6
github.com/puppetlabs/installer/wizard.mainModel.View({{0xe1dc30, 0xc0001d66e0}, {{0x1636060, 0x2, 0x2}, 0x0, 0x0, 0x1, 0xf, {0xbb3d04, ...}}, ...})
        /home/runner/work/installer/installer/wizard/mainModel.go:262 +0x4f
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc000323860, {0xe1dc60?, 0xc000198240?}, 0xc0005e55a8?)
        /home/runner/work/installer/installer/vendor/github.com/charmbracelet/bubbletea/tea.go:413 +0x798
github.com/charmbracelet/bubbletea.(*Program).Run(0xc000323860)
        /home/runner/work/installer/installer/vendor/github.com/charmbracelet/bubbletea/tea.go:543 +0x88e
github.com/puppetlabs/installer/wizard.Wizard({0xe17f68, 0x6}, {0xc0000d0040, 0x1a})
        /home/runner/work/installer/installer/wizard/wizard.go:27 +0x26d
github.com/puppetlabs/installer/cmd.glob..func1.WizardCmd.func1(0xc000030c00?, {0xb9d9a6?, 0x4?, 0xb9d9aa?})
        /home/runner/work/installer/installer/cmd/wizard.go:34 +0xdd
github.com/spf13/cobra.(*Command).execute(0xc0006cec00, {0xc00002e0b0, 0x0, 0x0})
        /home/runner/work/installer/installer/vendor/github.com/spf13/cobra/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0006cec00)
        /home/runner/work/installer/installer/vendor/github.com/spf13/cobra/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/installer/installer/vendor/github.com/spf13/cobra/command.go:1039
github.com/puppetlabs/installer/cmd.glob..func1(0xc000030900?, {0x168f6e0?, 0x7?, 0xb9d9aa?})
        /home/runner/work/installer/installer/cmd/root.go:48 +0x107
github.com/spf13/cobra.(*Command).execute(0x1619760, {0xc00002e0b0, 0x0, 0x0})
        /home/runner/work/installer/installer/vendor/github.com/spf13/cobra/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x1619760)
        /home/runner/work/installer/installer/vendor/github.com/spf13/cobra/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/installer/installer/vendor/github.com/spf13/cobra/command.go:1039
github.com/puppetlabs/installer/cmd.Execute({0xe17f68?, 0x4e?})
        /home/runner/work/installer/installer/cmd/root.go:73 +0xdf
main.main()
        /home/runner/work/installer/installer/main.go:22 +0xbd
```

## Expected Behavior
Install works.

## Steps to Reproduce
1. Execute PIM wizard on Windows, to install PE on remote node.

**Comment by cathal41** [comment]
This fix will be available in the next release of PIM - https://github.com/puppetlabs/installer/pull/481
The windows installer tries to render a progress bar outside of the console window causing this issue.
